name: DockerHub Deploy  # Name of the workflow

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Environment variable for DockerHub username
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Environment variable for DockerHub password
  REPO_NAME: ${{ secrets.REPO_NAME }}  # Environment variable for repository name

on:
  workflow_run:
    workflows: ["test"]  # Trigger this workflow when the "test" workflow completes
    types:
      - completed  # Trigger on completion of the "test" workflow

jobs:
  deploy:
    runs-on: self-hosted  # Run the job on a self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Login to DockerHub
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin  # Login to DockerHub using Docker credentials

      - name: Current time
        id: date
        run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"  # Get the current date and time and store it in an environment variable

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6  # Use the Docker Build and Push action
        with:
          username: ${{ env.DOCKER_USERNAME }}  # DockerHub username
          password: ${{ env.DOCKER_PASSWORD }}  # DockerHub password
          registry: docker.io  # Docker registry
          dockerfile: Dockerfile  # Path to Dockerfile
          tags: $date  # Tag for the Docker image (current date and time)
          image: ${{ env.DOCKER_USERNAME }}/${{ env.REPO_NAME }}  # Image name and repository on DockerHub
