name: DockerHub Deploy

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPO_NAME: ${{ secrets.REPO_NAME }}

on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Current time
              id: date
              run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"

            - name: Build and push Docker image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                username: janfalez
                password: jancar2003!
                registry: docker.io
                dockerfile: Dockerfile
                tags: $date
                image: janfalez/vaja3in4
