name: DockerHub Deploy

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPONAME: ${{ secrets.REPO_NAME }}

on:
    workflow_run:
        workflows: ["test"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
 
            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin

            - name: Build Docker image
              run: docker build -t $DOCKER_USERNAME/$REPONAME:latest
      
            - name: Push docker image
              run: |
                docker push $DOCKER_USERNAME/$REPONAME:latest
