name: DockerHub Deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPONAME: ${{ secrets.REPO_NAME }}

on:
  workflow_run:
    workflows: ["27107_test.yml"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    needs: check_tests
    if: ${{ needs.check_tests.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Current time
        id: datum
        run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"
        
      - name: Push to DockerHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: docker.io
          dockerfile: Dockerfile
          tags: ${{ env.REPONAME }}:$date
          image: ${{ env.DOCKER_USERNAME }}/${{ env.REPONAME }}
