name: DockerHub Deploy

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPONAME: ${{ secrets.REPO_NAME }}

on:
    workflow_run:
        workflows: ["test"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
 
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:latest .
              
            - name: Push docker image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPO_NAME }}:latest
