name: DockerHub Deploy

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPONAME: ${{ secrets.REPO_NAME }}

on:
    workflow_run:
        workflows: ["test"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
 
            - name: Login in Docker
              run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Current time
              id: date
              run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"

            - name: Build Docker image
              run: |
                echo ${{ steps.date.outputs.date }}
                echo "docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date"
                docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date
      
            - name: Push docker image
              run: |
                docker push $DOCKER_USERNAME/$REPONAME:$date
