name: DockerHub Deploy

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPO_NAME: ${{ secrets.REPO_NAME }}

on:
    workflow_run:
        workflows: ["test"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        container: debian:10
        services:
          docker:
            image: docker:19.03.12
            options: --privileged
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
            - name: Current time
              id: date
              run: echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"

            - name: Build and push Docker image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}
                registry: docker.io
                dockerfile: Dockerfile
                tags: $date
                image: ${{ env.DOCKER_USERNAME }}/${{ env.REPO_NAME }}
