name: DockerHub Deploy

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    REPONAME: ${{ secrets.REPO_NAME }}

on:
    workflow_run:
        workflows: ["test"]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
 
            - name: Login to Docker Hub
              run: sudo echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
            
            - name: Current time
              id: date
              run: sudo echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"

            - name: Build Docker image
              run: |
                sudo echo ${{ steps.date.outputs.date }}
                sudo echo "docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date"
                sudo docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date
      
            - name: Push docker image
              run: |
                sudo docker push $DOCKER_USERNAME/$REPONAME:$date
