name: CI

on:
  push:
    branches: [ main ]

jobs:
    check_tests:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.6, 3.7, 3.8, 3.9]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        
        - name: Check if test script exists
          run: |
            if [ ! -f "test.py" ]; then
              echo "Test script not found" > napaka.txt
              exit 1
            fi
          continue-on-error: true
          # Saves the error output to a file
          if: ${{ failure() }}
        
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: error-artifact
            path: napaka.txt
          if: ${{ failure() }}
  
    run_tests:
      runs-on: ubuntu-latest
      needs: check_tests
      strategy:
        matrix:
          python-version: [3.6, 3.7, 3.8, 3.9]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
  
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: error-artifact
            path: .
          if: ${{ needs.check_tests.result == 'failure' }}
  
        - name: Install dependencies
          run: pip install -r requirements.txt
  
        - name: Run tests
          run: python test.py
          continue-on-error: true
        
        - name: Check for error
          run: |
            if [ -f "napaka.txt" ]; then
              cat napaka.txt
              exit 1
            fi
          if: ${{ failure() }}
  